import type { IconType } from 'react-icons'
import {
  GiAnvil,
  GiBarricade,
  GiBookshelf,
  GiBoxTrap,
  GiBrickWall,
  GiBridge,
  GiCampingTent,
  GiCampfire,
  GiCargoCrate,
  GiCastle,
  GiClosedDoors,
  GiConcreteBag,
  GiDoor,
  GiElectric,
  GiFarmTractor,
  GiFire,
  GiGearHammer,
  GiGreenhouse,
  GiGuardedTower,
  GiHammerNails,
  GiHandSaw,
  GiHidden,
  GiHouse,
  GiLockpicks,
  GiMetalBar,
  GiOilPump,
  GiPadlock,
  GiPalisade,
  GiRopeCoil,
  GiShop,
  GiShower,
  GiStoneTower,
  GiTable,
  GiWatchtower,
  GiWaterDrop,
  GiWaterRecycling,
  GiWaterTank,
  GiWell,
  GiWindmill,
  GiWoodenCrate,
  GiWoodenDoor,
  GiWoodenFence,
  GiWoodPile,
} from 'react-icons/gi'
import type { SettlementConstructionCategory } from '@/config/settlementConstructions'

const CATEGORY_ICONS: Record<SettlementConstructionCategory, IconType> = {
  podstawowe: GiHammerNails,
  schronienia: GiCampingTent,
  mechaniczne: GiGearHammer,
  pulapki: GiBoxTrap,
  obrona: GiCastle,
  budynki: GiHouse,
  infrastruktura: GiConcreteBag,
}

/** Per-construction icons; falls back to category icon. */
const KEY_ICONS: Record<string, IconType> = {
  barykada: GiBarricade,
  palenisko: GiCampfire,
  prowizoryczne_drzwi: GiWoodenDoor,
  polka: GiBookshelf,
  regal: GiBookshelf,
  rygiel: GiPadlock,
  stojak: GiWoodenCrate,
  stol_roboczy: GiTable,
  suszarnia: GiWoodPile,
  zadaszenie: GiHouse,
  zbiornik_na_wode: GiWaterTank,

  latryna: GiWaterRecycling,
  namiot: GiCampingTent,
  skladowisko: GiCargoCrate,
  szopa: GiWoodenCrate,
  wiata: GiShop,
  magazyn: GiCargoCrate,
  piec: GiFire,
  prysznic_polowy: GiShower,
  spizarnia: GiWoodenCrate,
  stol_warsztatowy: GiTable,
  warsztat: GiHandSaw,
  wedzarnia: GiFire,
  kuznia: GiAnvil,

  bloczek: GiRopeCoil,
  dzwignia: GiMetalBar,
  rampa: GiBridge,
  taczka: GiCargoCrate,
  wozek_transportowy: GiCargoCrate,
  kolowrot: GiGearHammer,
  wciagarka_linowa: GiRopeCoil,
  wciagarka_reczna: GiRopeCoil,
  wielokrazek: GiRopeCoil,
  prosty_zuraw: GiGearHammer,
  wozek_na_szynach: GiCargoCrate,
  zuraw_obrotowy: GiGearHammer,

  alarm_na_sznurku: GiHidden,
  dzwonki_alarmowe: GiHidden,
  przeszkoda: GiBarricade,
  pulapka_na_drzwi: GiClosedDoors,
  ukryta_linka: GiHidden,
  alarm_mechaniczny: GiHidden,
  kolczasta_przeszkoda: GiWoodenFence,
  mechanizm_blokujacy: GiLockpicks,
  pulapka_na_pojazdy: GiBoxTrap,
  pulapka_zaciskowa: GiBoxTrap,
  row: GiConcreteBag,
  zapadnia: GiHidden,
  strefa_pulapek: GiBoxTrap,
  system_kierowania_ruchu: GiBarricade,

  furtka: GiDoor,
  okiennica: GiClosedDoors,
  plot: GiWoodenFence,
  brama: GiDoor,
  kraty: GiMetalBar,
  palisada: GiPalisade,
  row_obronny: GiConcreteBag,
  stanowisko_obserwacyjne: GiWatchtower,
  wal_ziemny: GiBrickWall,
  wzmocniona_barykada: GiBarricade,
  wzmocniony_plot: GiWoodenFence,
  brama_warowna: GiCastle,
  mur: GiBrickWall,
  stanowisko_ochronne: GiGuardedTower,
  wieza_straznicza: GiWatchtower,
  wzmocniony_mur: GiBrickWall,
  mur_forteczny: GiCastle,

  szalas: GiCampingTent,
  chata: GiHouse,
  stodola: GiShop,
  domek: GiHouse,
  garaz: GiShop,
  rusznikarnia: GiAnvil,
  budynek_mieszkalny: GiHouse,
  dom: GiHouse,
  hala: GiShop,
  umocniony_budynek: GiCastle,

  system_zbierania_deszczowki: GiWaterDrop,
  cysterna: GiWaterTank,
  droga: GiConcreteBag,
  pompa_wodna: GiOilPump,
  studnia: GiWell,
  szklarnia: GiGreenhouse,
  wieza_obserwacyjna: GiStoneTower,
  farma: GiFarmTractor,
  generator: GiElectric,
  instalacja_elektryczna: GiElectric,
  most: GiBridge,
  mlyn: GiWindmill,
  system_kanalizacyjny: GiWaterDrop,
}

export function settlementConstructionIcon(
  catalogKey: string,
  category?: SettlementConstructionCategory,
): IconType {
  return KEY_ICONS[catalogKey]
    ?? (category ? CATEGORY_ICONS[category] : undefined)
    ?? GiHammerNails
}
