import type { SettlementMaterialKey } from '@/config/settlementMaterials'

export type SettlementConstructionCategory =
  | 'podstawowe'
  | 'schronienia'
  | 'mechaniczne'
  | 'pulapki'
  | 'obrona'
  | 'budynki'
  | 'infrastruktura'

export const SETTLEMENT_CONSTRUCTION_CATEGORIES: SettlementConstructionCategory[] = [
  'podstawowe',
  'schronienia',
  'mechaniczne',
  'pulapki',
  'obrona',
  'budynki',
  'infrastruktura',
]

export type ConstructionMaterialCost = Partial<Record<SettlementMaterialKey, number>>

export interface SettlementConstructionDef {
  key: string
  /** Polish display name (system docs). */
  name: string
  /** English display name. */
  nameEn: string
  category: SettlementConstructionCategory
  complexity: number
  time: number
  materials: ConstructionMaterialCost
  properties: string
  description: string
  descriptionEn: string
}

function c(
  key: string,
  name: string,
  nameEn: string,
  category: SettlementConstructionCategory,
  complexity: number,
  time: number,
  materials: ConstructionMaterialCost,
  properties: string,
  description: string,
  descriptionEn: string,
): SettlementConstructionDef {
  return {
    key, name, nameEn, category, complexity, time, materials, properties, description, descriptionEn,
  }
}

/** Full construction catalog from system docs (Konstrukcje). */
export const SETTLEMENT_CONSTRUCTIONS: SettlementConstructionDef[] = [
  c('barykada', 'Barykada', 'Barricade', 'podstawowe', 1, 1, { drewno: 3, spoiwa: 1 }, '',
    'Prosta przeszkoda blokująca przejście i utrudniająca przedostanie się przez zabezpieczony otwór.',
    'A simple obstacle blocking a passage.'),
  c('palenisko', 'Palenisko', 'Hearth', 'podstawowe', 1, 1, { kamien: 2 }, '',
    'Miejsce do rozpalania ognia, gotowania i ogrzewania.',
    'A place for fire, cooking and heating.'),
  c('prowizoryczne_drzwi', 'Prowizoryczne drzwi', 'Makeshift door', 'podstawowe', 1, 2, { drewno: 3, spoiwa: 1 }, '',
    'Proste drzwi wykonane z dostępnych materiałów, pozwalające zamknąć istniejący otwór.',
    'Simple door made from available materials.'),
  c('polka', 'Półka', 'Shelf', 'podstawowe', 1, 1, { drewno: 2, spoiwa: 1 }, '',
    'Prosta konstrukcja do przechowywania wyposażenia i zapasów.',
    'Simple storage shelf.'),
  c('regal', 'Regał', 'Rack', 'podstawowe', 1, 2, { drewno: 4, spoiwa: 1 }, '',
    'Większa konstrukcja do uporządkowanego przechowywania wyposażenia i zapasów.',
    'Larger organized storage rack.'),
  c('rygiel', 'Rygiel', 'Bolt latch', 'podstawowe', 1, 1, { drewno: 1, metal: 1, spoiwa: 1 }, '✚Obronny',
    'Proste mechaniczne zamknięcie wzmacniające drzwi lub bramę.',
    'Simple mechanical latch reinforcing a door or gate.'),
  c('stojak', 'Stojak', 'Stand', 'podstawowe', 1, 1, { drewno: 2, spoiwa: 1 }, '',
    'Prosta konstrukcja do przechowywania lub eksponowania wyposażenia.',
    'Simple stand for storing or displaying gear.'),
  c('stol_roboczy', 'Stół roboczy', 'Work table', 'podstawowe', 1, 2, { drewno: 4, spoiwa: 1 }, '✚Warsztat',
    'Proste stanowisko umożliwiające wykonywanie podstawowych prac i craftingu.',
    'Basic workstation for crafting.'),
  c('suszarnia', 'Suszarnia', 'Drying rack', 'podstawowe', 1, 2, { drewno: 2, spoiwa: 1 }, '',
    'Prosta konstrukcja umożliwiająca suszenie żywności, ziół i innych materiałów.',
    'Structure for drying food, herbs and materials.'),
  c('zadaszenie', 'Zadaszenie', 'Canopy', 'podstawowe', 1, 2, { drewno: 2, spoiwa: 1 }, '',
    'Prosta konstrukcja chroniąca przed deszczem, śniegiem i słońcem.',
    'Simple cover against weather.'),
  c('zbiornik_na_wode', 'Zbiornik na wodę', 'Water tank', 'podstawowe', 1, 1, { drewno: 1, spoiwa: 1 }, '✚Pojemny',
    'Prosta konstrukcja umożliwiająca gromadzenie i przechowywanie wody.',
    'Simple water storage.'),

  c('latryna', 'Latryna', 'Latrine', 'schronienia', 1, 2, { drewno: 2, spoiwa: 1 }, '✚Higieniczny',
    'Prosta konstrukcja przeznaczona do bezpiecznego odprowadzania nieczystości.',
    'Simple sanitary waste structure.'),
  c('namiot', 'Namiot', 'Tent', 'schronienia', 1, 1, { drewno: 1, spoiwa: 1 }, '✚Przenośny',
    'Lekkie, tymczasowe schronienie zapewniające podstawową ochronę przed warunkami atmosferycznymi.',
    'Light temporary shelter.'),
  c('skladowisko', 'Składowisko', 'Stockpile', 'schronienia', 1, 1, { drewno: 2 }, '✚Pojemny',
    'Wyznaczone i przygotowane miejsce do przechowywania dużych ilości materiałów.',
    'Prepared area for bulk material storage.'),
  c('szopa', 'Szopa', 'Shed', 'schronienia', 1, 3, { drewno: 6, metal: 1, spoiwa: 2 }, '',
    'Prosty zamknięty obiekt do przechowywania narzędzi, materiałów i sprzętu.',
    'Simple closed shed for tools and materials.'),
  c('wiata', 'Wiata', 'Lean-to', 'schronienia', 1, 2, { drewno: 4, spoiwa: 1 }, '',
    'Zadaszona, otwarta konstrukcja zapewniająca miejsce do pracy lub przechowywania wyposażenia.',
    'Open roofed structure for work or storage.'),
  c('magazyn', 'Magazyn', 'Warehouse', 'schronienia', 2, 4, { drewno: 8, metal: 3, spoiwa: 2 }, '✚Pojemny',
    'Zamknięty obiekt przeznaczony do bezpiecznego przechowywania zapasów i wyposażenia.',
    'Closed building for secure storage.'),
  c('piec', 'Piec', 'Oven', 'schronienia', 2, 3, { kamien: 4, metal: 1, spoiwa: 1 }, '✚Ognioodporny',
    'Konstrukcja umożliwiająca gotowanie, ogrzewanie oraz obróbkę materiałów wymagających wysokiej temperatury.',
    'Structure for cooking, heating and high-temperature work.'),
  c('prysznic_polowy', 'Prysznic polowy', 'Field shower', 'schronienia', 2, 2, { drewno: 2, spoiwa: 1 }, '',
    'Prosta instalacja umożliwiająca utrzymanie higieny osobistej.',
    'Simple personal hygiene installation.'),
  c('spizarnia', 'Spiżarnia', 'Pantry', 'schronienia', 2, 3, { drewno: 6, metal: 1, kamien: 1, spoiwa: 2 }, '✚Izolowany',
    'Pomieszczenie przeznaczone do przechowywania żywności i zapasów wymagających ochrony przed warunkami zewnętrznymi.',
    'Room for food and supplies needing protection.'),
  c('stol_warsztatowy', 'Stół warsztatowy', 'Workbench', 'schronienia', 2, 3, { drewno: 4, metal: 2, spoiwa: 2 }, '✚Warsztat2',
    'Solidne stanowisko umożliwiające wykonywanie zaawansowanych prac mechanicznych i rzemieślniczych.',
    'Solid station for advanced mechanical work.'),
  c('warsztat', 'Warsztat', 'Workshop', 'schronienia', 2, 4, { drewno: 6, metal: 3, spoiwa: 2 }, '✚Warsztat',
    'Pomieszczenie przeznaczone do naprawy, obróbki materiałów i wykonywania bardziej złożonych konstrukcji.',
    'Room for repairs and complex construction work.'),
  c('wedzarnia', 'Wędzarnia', 'Smokehouse', 'schronienia', 2, 3, { kamien: 3, drewno: 2 }, '',
    'Konstrukcja umożliwiająca konserwowanie żywności poprzez wędzenie.',
    'Structure for smoking and preserving food.'),
  c('kuznia', 'Kuźnia', 'Forge', 'schronienia', 3, 5, { kamien: 6, metal: 3, spoiwa: 2 }, '✚Ognioodporny2 ✚Produkcja2',
    'Stanowisko umożliwiające obróbkę metalu przy użyciu wysokiej temperatury.',
    'Station for high-temperature metalworking.'),

  c('bloczek', 'Bloczek', 'Pulley', 'mechaniczne', 1, 1, { drewno: 1, metal: 1, spoiwa: 1 }, '✚Wspomagający',
    'Proste urządzenie zmieniające kierunek działania siły i ułatwiające podnoszenie ładunków.',
    'Simple pulley for lifting loads.'),
  c('dzwignia', 'Dźwignia', 'Lever', 'mechaniczne', 1, 1, { drewno: 1, metal: 1 }, '✚Wspomagający',
    'Proste urządzenie wykorzystujące zasadę dźwigni do przesuwania lub podnoszenia ciężkich przedmiotów.',
    'Lever for moving or lifting heavy objects.'),
  c('rampa', 'Rampa', 'Ramp', 'mechaniczne', 1, 1, { drewno: 3, spoiwa: 1 }, '✚Wspomagający',
    'Pochyła konstrukcja ułatwiająca przemieszczanie ciężkich przedmiotów na inną wysokość.',
    'Inclined structure for moving heavy objects.'),
  c('taczka', 'Taczka', 'Wheelbarrow', 'mechaniczne', 1, 2, { drewno: 2, metal: 1, spoiwa: 1 }, '✚Logistyka',
    'Proste urządzenie umożliwiające transport ciężkich materiałów przez jedną osobę.',
    'One-person cart for heavy materials.'),
  c('wozek_transportowy', 'Wózek transportowy', 'Hand cart', 'mechaniczne', 1, 2, { drewno: 3, metal: 2, spoiwa: 1 }, '✚Logistyka',
    'Konstrukcja umożliwiająca przemieszczanie większej ilości materiałów przy mniejszym wysiłku.',
    'Cart for moving larger material loads.'),
  c('kolowrot', 'Kołowrót', 'Winch drum', 'mechaniczne', 2, 2, { drewno: 2, metal: 2, spoiwa: 1 }, '✚Wspomagający',
    'Mechanizm wykorzystujący obrót do podnoszenia, opuszczania lub napinania ciężkich przedmiotów.',
    'Rotary mechanism for lifting or tensioning.'),
  c('wciagarka_linowa', 'Wciągarka linowa', 'Rope hoist', 'mechaniczne', 2, 3, { metal: 3, spoiwa: 2 }, '✚Wspomagający2',
    'Mechanizm umożliwiający przeciąganie ciężkich przedmiotów przy użyciu liny.',
    'Mechanism for hauling loads with rope.'),
  c('wciagarka_reczna', 'Wciągarka ręczna', 'Hand winch', 'mechaniczne', 2, 3, { metal: 3, spoiwa: 2 }, '✚Wspomagający2',
    'Mechanizm umożliwiający podnoszenie lub przeciąganie ciężkich przedmiotów przy użyciu ręcznej siły.',
    'Hand-powered winch for lifting or hauling.'),
  c('wielokrazek', 'Wielokrążek', 'Block and tackle', 'mechaniczne', 2, 3, { drewno: 2, metal: 3, spoiwa: 2 }, '✚Wspomagający2',
    'Układ bloczków pozwalający znacząco zmniejszyć siłę potrzebną do podnoszenia ciężkich ładunków.',
    'Pulley system reducing force needed to lift loads.'),
  c('prosty_zuraw', 'Prosty żuraw', 'Simple crane', 'mechaniczne', 3, 4, { drewno: 5, metal: 3, spoiwa: 2 }, '✚Wspomagający2',
    'Konstrukcja umożliwiająca podnoszenie i przemieszczanie ciężkich ładunków.',
    'Structure for lifting and moving heavy loads.'),
  c('wozek_na_szynach', 'Wózek na szynach', 'Rail cart', 'mechaniczne', 3, 5, { drewno: 4, metal: 5, spoiwa: 2 }, '✚Logistyka2',
    'Wózek poruszający się po stałej trasie, umożliwiający transport ciężkich ładunków.',
    'Cart on a fixed track for heavy transport.'),
  c('zuraw_obrotowy', 'Żuraw obrotowy', 'Slewing crane', 'mechaniczne', 3, 5, { drewno: 5, metal: 5, spoiwa: 3 }, '✚Wspomagający3',
    'Żuraw umożliwiający podnoszenie oraz przemieszczanie ładunków w różnych kierunkach.',
    'Crane that lifts and swings loads in multiple directions.'),

  c('alarm_na_sznurku', 'Alarm na sznurku', 'Tripwire alarm', 'pulapki', 1, 1, { spoiwa: 1 }, '✚Głośny',
    'Prosty mechanizm uruchamiający sygnał po naruszeniu napiętej linki.',
    'Simple alarm triggered by a trip line.'),
  c('dzwonki_alarmowe', 'Dzwonki alarmowe', 'Alarm bells', 'pulapki', 1, 1, { metal: 1, spoiwa: 1 }, '✚Głośny',
    'Mechanizm wydający głośny dźwięk po naruszeniu zabezpieczenia.',
    'Loud bells triggered by a breach.'),
  c('przeszkoda', 'Przeszkoda', 'Obstacle', 'pulapki', 1, 1, { drewno: 2, spoiwa: 1 }, '✚Ukryty',
    'Prosta przeszkoda umieszczona w sposób utrudniający lub spowalniający przejście.',
    'Obstacle that slows or hinders passage.'),
  c('pulapka_na_drzwi', 'Pułapka na drzwi', 'Door trap', 'pulapki', 1, 1, { metal: 1, spoiwa: 1 }, '✚Głośny',
    'Prosty mechanizm informujący o otwarciu zabezpieczonych drzwi.',
    'Mechanism that signals a secured door opening.'),
  c('ukryta_linka', 'Ukryta linka', 'Hidden line', 'pulapki', 1, 1, { spoiwa: 1 }, '✚Ukryty',
    'Niewidoczna lub trudna do zauważenia linka uruchamiająca przygotowany mechanizm po jej naruszeniu.',
    'Hard-to-spot line that triggers a prepared mechanism.'),
  c('alarm_mechaniczny', 'Alarm mechaniczny', 'Mechanical alarm', 'pulapki', 2, 2, { metal: 1, spoiwa: 2 }, '✚Głośny2',
    'Bardziej złożony mechanizm uruchamiający sygnał alarmowy po wykryciu naruszenia.',
    'More complex alarm triggered by intrusion.'),
  c('kolczasta_przeszkoda', 'Kolczasta przeszkoda', 'Spiked barrier', 'pulapki', 2, 2, { drewno: 2, metal: 2, spoiwa: 1 }, '✚Ciernie',
    'Konstrukcja z wystającymi ostrymi elementami utrudniająca przejście przez zabezpieczony obszar.',
    'Barrier with sharp elements hindering passage.'),
  c('mechanizm_blokujacy', 'Mechanizm blokujący', 'Locking mechanism', 'pulapki', 2, 2, { metal: 2, spoiwa: 2 }, '',
    'Mechanizm automatycznie blokujący przejście lub element konstrukcji po jego uruchomieniu.',
    'Mechanism that auto-locks a passage when triggered.'),
  c('pulapka_na_pojazdy', 'Pułapka na pojazdy', 'Vehicle trap', 'pulapki', 2, 2, { drewno: 2, metal: 2, spoiwa: 1 }, '✚Unieruchamiający',
    'Konstrukcja przeznaczona do zatrzymywania lub utrudniania przejazdu pojazdom.',
    'Trap meant to stop or hinder vehicles.'),
  c('pulapka_zaciskowa', 'Pułapka zaciskowa', 'Snare trap', 'pulapki', 2, 3, { metal: 2, spoiwa: 2 }, '✚Unieruchamiający',
    'Mechanizm zaciskający się po uruchomieniu i ograniczający możliwość ruchu celu.',
    'Trap that clamps and restricts target movement.'),
  c('row', 'Rów', 'Ditch', 'pulapki', 2, 4, {}, '✚Spowalniający',
    'Wykopana przeszkoda terenowa utrudniająca przejście lub przejazd.',
    'Dug terrain obstacle slowing passage.'),
  c('zapadnia', 'Zapadnia', 'Pitfall', 'pulapki', 2, 3, { drewno: 4, metal: 1, spoiwa: 2 }, '✚Ukryty',
    'Mechanizm otwierający przygotowany otwór po uruchomieniu.',
    'Mechanism that opens a prepared pit when triggered.'),
  c('strefa_pulapek', 'Strefa pułapek', 'Trap zone', 'pulapki', 3, 5, { drewno: 4, metal: 2, spoiwa: 3 }, '✚Ciernie2',
    'Obszar wyposażony w kilka współdziałających pułapek utrudniających lub uniemożliwiających przejście.',
    'Area with several cooperating traps.'),
  c('system_kierowania_ruchu', 'System kierowania ruchu', 'Funnel system', 'pulapki', 3, 4, { drewno: 5, metal: 2, spoiwa: 3 }, '',
    'Układ przeszkód i mechanizmów zmuszający osoby lub stworzenia do poruszania się określoną trasą.',
    'Obstacle layout forcing movement along a set path.'),

  c('furtka', 'Furtka', 'Wicket gate', 'obrona', 1, 2, { drewno: 2, metal: 1, spoiwa: 1 }, '',
    'Małe, kontrolowane przejście w ogrodzeniu lub umocnieniu.',
    'Small controlled passage in a fence.'),
  c('okiennica', 'Okiennica', 'Shutter', 'obrona', 1, 1, { drewno: 2, spoiwa: 1 }, '✚Obronny',
    'Ruchoma osłona zabezpieczająca otwór okienny.',
    'Movable cover securing a window opening.'),
  c('plot', 'Płot', 'Fence', 'obrona', 1, 3, { drewno: 4, spoiwa: 1 }, '',
    'Proste ogrodzenie wyznaczające granicę i utrudniające przejście.',
    'Simple fence marking a boundary.'),
  c('brama', 'Brama', 'Gate', 'obrona', 2, 3, { drewno: 4, metal: 2, spoiwa: 2 }, '✚Obronny',
    'Kontrolowane przejście pozwalające otwierać i zamykać ogrodzony obszar.',
    'Controlled gate for an enclosed area.'),
  c('kraty', 'Kraty', 'Bars', 'obrona', 2, 3, { metal: 3, spoiwa: 2 }, '✚Obronny2',
    'Metalowa konstrukcja zabezpieczająca drzwi, okna lub inne otwory.',
    'Metal bars securing doors, windows or openings.'),
  c('palisada', 'Palisada', 'Palisade', 'obrona', 2, 4, { drewno: 8, spoiwa: 2 }, '✚Obronny2',
    'Ciężka drewniana fortyfikacja utrudniająca przedostanie się do chronionego obszaru.',
    'Heavy wooden fortification.'),
  c('row_obronny', 'Rów obronny', 'Defensive ditch', 'obrona', 2, 5, {}, '✚Obronny2',
    'Głęboki wykop utrudniający dostęp do chronionego obszaru.',
    'Deep ditch hindering access.'),
  c('stanowisko_obserwacyjne', 'Stanowisko obserwacyjne', 'Observation post', 'obrona', 2, 3, { drewno: 4, spoiwa: 2 }, '✚Pozycja obserwacyjna2',
    'Podwyższone lub osłonięte miejsce umożliwiające obserwację otoczenia.',
    'Raised or covered post for watching surroundings.'),
  c('wal_ziemny', 'Wał ziemny', 'Earthen rampart', 'obrona', 2, 4, { kamien: 3 }, '✚Obronny2',
    'Nasyp ziemny zapewniający osłonę i mogący stanowić podstawę innych umocnień.',
    'Earthen embankment for cover and fortifications.'),
  c('wzmocniona_barykada', 'Wzmocniona barykada', 'Reinforced barricade', 'obrona', 2, 2, { drewno: 3, metal: 2, spoiwa: 2 }, '✚Wytrzymały2',
    'Wzmocniona konstrukcja blokująca przejście i wytrzymująca większe obciążenia.',
    'Reinforced barrier that withstands greater force.'),
  c('wzmocniony_plot', 'Wzmocniony płot', 'Reinforced fence', 'obrona', 2, 4, { drewno: 5, metal: 2, spoiwa: 2 }, '✚Wytrzymały2',
    'Solidniejsze ogrodzenie przeznaczone do ochrony obozu lub posesji.',
    'Sturdier fence for camp or property defense.'),
  c('brama_warowna', 'Brama warowna', 'Fortified gate', 'obrona', 3, 5, { drewno: 6, metal: 4, spoiwa: 3 }, '✚Wytrzymały3',
    'Silnie zabezpieczona brama przeznaczona do ochrony głównego wejścia.',
    'Heavily secured main entrance gate.'),
  c('mur', 'Mur', 'Wall', 'obrona', 3, 5, { kamien: 8, metal: 1, spoiwa: 3 }, '✚Wytrzymały3',
    'Trwała konstrukcja wykonana z ciężkich materiałów, zapewniająca skuteczne odgrodzenie i ochronę.',
    'Durable heavy wall for enclosure and protection.'),
  c('stanowisko_ochronne', 'Stanowisko ochronne', 'Defensive post', 'obrona', 3, 4, { drewno: 3, metal: 3, kamien: 2, spoiwa: 2 }, '✚Obronny3',
    'Osłonięte stanowisko umożliwiające bezpieczną obserwację i obronę terenu.',
    'Covered post for safe observation and defense.'),
  c('wieza_straznicza', 'Wieża strażnicza', 'Watchtower', 'obrona', 3, 5, { drewno: 8, metal: 2, spoiwa: 3 }, '✚Pozycja obserwacyjna3',
    'Wysoka konstrukcja zapewniająca szeroki widok na otoczenie i umożliwiająca wczesne wykrywanie zagrożeń.',
    'Tall structure for wide view and early warning.'),
  c('wzmocniony_mur', 'Wzmocniony mur', 'Reinforced wall', 'obrona', 4, 6, { kamien: 10, metal: 3, spoiwa: 4 }, '✚Wytrzymały4',
    'Solidny mur przystosowany do wytrzymywania znacznych obciążeń i ataków.',
    'Solid wall built to withstand heavy attacks.'),
  c('mur_forteczny', 'Mur forteczny', 'Fortress wall', 'obrona', 5, 6, { kamien: 15, metal: 5, spoiwa: 5 }, '✚Wytrzymały5',
    'Ciężkie umocnienie zaprojektowane do długotrwałej ochrony dużego obszaru.',
    'Heavy fortification for long-term area defense.'),

  c('szalas', 'Szałas', 'Hut', 'budynki', 1, 2, { drewno: 3, spoiwa: 1 }, '',
    'Minimalne, tymczasowe schronienie wykonane z łatwo dostępnych materiałów.',
    'Minimal temporary shelter from available materials.'),
  c('chata', 'Chata', 'Cabin', 'budynki', 2, 4, { drewno: 8, kamien: 2, spoiwa: 2 }, '✚Mieszkalny',
    'Prosty, zamknięty budynek zapewniający podstawowe warunki do życia.',
    'Simple closed building for basic living.'),
  c('stodola', 'Stodoła', 'Barn', 'budynki', 2, 5, { drewno: 12, metal: 3, spoiwa: 3 }, '✚Pojemny2',
    'Duży obiekt przeznaczony do przechowywania materiałów, narzędzi lub zapasów.',
    'Large building for materials, tools or supplies.'),
  c('domek', 'Domek', 'Cottage', 'budynki', 3, 5, { drewno: 12, kamien: 3, szklo: 2, spoiwa: 4 }, '✚Mieszkalny2',
    'Pełnoprawny niewielki budynek mieszkalny zapewniający ochronę przed warunkami zewnętrznymi.',
    'Proper small residential building.'),
  c('garaz', 'Garaż', 'Garage', 'budynki', 3, 5, { drewno: 8, metal: 5, spoiwa: 4 }, '✚Warsztat',
    'Zadaszony i zamykany obiekt przeznaczony do przechowywania oraz naprawy pojazdów.',
    'Enclosed building for storing and repairing vehicles.'),
  c('rusznikarnia', 'Rusznikarnia', 'Armory workshop', 'budynki', 3, 5, { drewno: 6, metal: 4, chemia: 2, spoiwa: 3 }, '✚Warsztat2 ✚Produkcja2',
    'Stanowisko do naprawy broni oraz produkcji amunicji (wymaga Metalu i Chemii).',
    'Station for weapon repair and ammo production.'),
  c('budynek_mieszkalny', 'Budynek mieszkalny', 'Residential building', 'budynki', 4, 6, { drewno: 18, kamien: 6, metal: 4, szklo: 3, spoiwa: 6 }, '✚Mieszkalny3',
    'Duży budynek przeznaczony do zakwaterowania większej liczby osób.',
    'Large building for housing more people.'),
  c('dom', 'Dom', 'House', 'budynki', 4, 6, { drewno: 18, kamien: 8, metal: 4, szklo: 4, spoiwa: 6 }, '✚Mieszkalny4',
    'Kompletny budynek mieszkalny zapewniający przestrzeń do życia i przechowywania wyposażenia.',
    'Full residential house with living and storage space.'),
  c('hala', 'Hala', 'Hall', 'budynki', 4, 6, { drewno: 15, metal: 8, kamien: 4, spoiwa: 6 }, '✚Pojemny4',
    'Duża konstrukcja zapewniająca znaczną przestrzeń użytkową.',
    'Large structure providing substantial usable space.'),
  c('umocniony_budynek', 'Umocniony budynek', 'Fortified building', 'budynki', 4, 6, { drewno: 10, metal: 6, kamien: 6, spoiwa: 5 }, '✚Obronny3',
    'Budynek przystosowany do pełnienia jednocześnie funkcji mieszkalnej i obronnej.',
    'Building serving both living and defensive roles.'),

  c('system_zbierania_deszczowki', 'System zbierania deszczówki', 'Rainwater system', 'infrastruktura', 2, 3, { drewno: 2, metal: 1, spoiwa: 2 }, '✚Woda',
    'Układ umożliwiający zbieranie i kierowanie wody opadowej do zbiornika.',
    'Setup for collecting rainwater into a tank.'),
  c('cysterna', 'Cysterna', 'Cistern', 'infrastruktura', 3, 5, { metal: 5, spoiwa: 3 }, '✚Pojemny3',
    'Duży zbiornik przeznaczony do przechowywania znacznych ilości wody.',
    'Large tank for storing significant water volumes.'),
  c('droga', 'Droga', 'Road', 'infrastruktura', 3, 5, { kamien: 8 }, '✚Logistyka2',
    'Przygotowana trasa ułatwiająca przemieszczanie ludzi, pojazdów i ładunków.',
    'Prepared route for people, vehicles and cargo.'),
  c('pompa_wodna', 'Pompa wodna', 'Water pump', 'infrastruktura', 3, 4, { metal: 3, spoiwa: 2 }, '✚Woda2',
    'Urządzenie umożliwiające przemieszczanie wody pomiędzy zbiornikami lub instalacjami.',
    'Device for moving water between tanks or systems.'),
  c('studnia', 'Studnia', 'Well', 'infrastruktura', 3, 6, { kamien: 8, metal: 2, spoiwa: 2 }, '✚Woda3',
    'Konstrukcja zapewniająca dostęp do wody gruntowej.',
    'Structure providing access to groundwater.'),
  c('szklarnia', 'Szklarnia', 'Greenhouse', 'infrastruktura', 3, 5, { drewno: 4, metal: 2, szklo: 6, spoiwa: 2 }, '✚Produkcja2',
    'Konstrukcja umożliwiająca uprawę roślin w kontrolowanych warunkach.',
    'Structure for growing plants in controlled conditions.'),
  c('wieza_obserwacyjna', 'Wieża obserwacyjna', 'Observation tower', 'infrastruktura', 3, 5, { drewno: 8, metal: 2, spoiwa: 3 }, '✚Pozycja obserwacyjna3',
    'Wysoka konstrukcja zapewniająca kontrolę nad rozległym obszarem.',
    'Tall structure for overlooking a wide area.'),
  c('farma', 'Farma', 'Farm', 'infrastruktura', 4, 6, { drewno: 8, kamien: 3, metal: 2, spoiwa: 3 }, '✚Produkcja4',
    'Zorganizowany obszar przeznaczony do stałej produkcji żywności.',
    'Organized area for ongoing food production.'),
  c('generator', 'Generator', 'Generator', 'infrastruktura', 4, 6, { metal: 5, kamien: 3, elektryka: 5, spoiwa: 4 }, '✚Energia5 −Skomplikowany2',
    'Obiekt przeznaczony do produkcji i obsługi energii elektrycznej.',
    'Facility for producing and handling electrical power.'),
  c('instalacja_elektryczna', 'Instalacja elektryczna', 'Electrical grid', 'infrastruktura', 4, 5, { metal: 2, elektryka: 5, spoiwa: 3 }, '✚Energia3 −Skomplikowany2',
    'System przewodów i urządzeń umożliwiający dystrybucję energii po osadzie.',
    'Wiring system distributing power across the settlement.'),
  c('most', 'Most', 'Bridge', 'infrastruktura', 4, 6, { drewno: 12, metal: 5, kamien: 5, spoiwa: 5 }, '✚Logistyka4 −Skomplikowany2',
    'Konstrukcja umożliwiająca przekraczanie rzek, przepaści i innych przeszkód terenowych.',
    'Structure for crossing rivers, gaps and terrain obstacles.'),
  c('mlyn', 'Młyn', 'Mill', 'infrastruktura', 4, 6, { drewno: 8, metal: 4, kamien: 4, spoiwa: 3 }, '✚Produkcja3 −Skomplikowany',
    'Konstrukcja umożliwiająca przetwarzanie zbóż na mąkę.',
    'Structure for milling grain into flour.'),
  c('system_kanalizacyjny', 'System kanalizacyjny', 'Sewage system', 'infrastruktura', 4, 6, { kamien: 8, metal: 3, spoiwa: 5 }, '✚Higieniczny4 −Skomplikowany2',
    'Rozbudowany system odprowadzania ścieków i nieczystości z osady.',
    'Extended system for draining settlement waste.'),
]

const BY_KEY = new Map(SETTLEMENT_CONSTRUCTIONS.map((item) => [item.key, item]))

export function getSettlementConstruction(key: string): SettlementConstructionDef | undefined {
  return BY_KEY.get(key)
}

export function constructionsByCategory(
  category: SettlementConstructionCategory,
): SettlementConstructionDef[] {
  return SETTLEMENT_CONSTRUCTIONS.filter((item) => item.category === category)
}

export function constructionLocalizedName(
  def: SettlementConstructionDef,
  lang: string,
): string {
  return lang.startsWith('en') ? def.nameEn : def.name
}

export function constructionLocalizedDescription(
  def: SettlementConstructionDef,
  lang: string,
): string {
  return lang.startsWith('en') ? def.descriptionEn : def.description
}
